// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PortfolioApi.Data;

#nullable disable

namespace PortfolioApi.Migrations
{
    [DbContext(typeof(PortfolioDb))]
    partial class PortfolioDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PortfolioApi.Models.Experience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Company")
                        .HasColumnType("text");

                    b.Property<string>("Date")
                        .HasColumnType("text");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Experiences");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Company = "Cardiff University",
                            Date = "2023 - 2026",
                            Details = "Studying Applied Software Engineering. Built an AI triage system for Signum Health (.NET, React, Python), a patient tracking system for the Welsh Blood Service (SpringBoot, Thymeleaf), and an accessible game discovery platform.",
                            Title = "Client Projects & BSc Software Engineering"
                        },
                        new
                        {
                            Id = 2,
                            Company = "Self-Employed",
                            Date = "Ongoing",
                            Details = "Designed and deployed a personal portfolio using Spring Boot, CI/CD, and Docker. Created a house renting site handling 100+ monthly visitors, and developed a custom WordPress site for a local business.",
                            Title = "Freelance Web Developer"
                        },
                        new
                        {
                            Id = 3,
                            Company = "CyberFirst",
                            Date = "August 2022",
                            Details = "Attended the CyberFirst program in Belfast, gaining valuable insights into the cybersecurity industry, threat landscapes, and defensive strategies.",
                            Title = "CyberFirst Attendee"
                        },
                        new
                        {
                            Id = 4,
                            Company = "Bumble Hole Foods",
                            Date = "Summer 2025",
                            Details = "Managed booking and dispatch for 100+ weekly deliveries. Optimised warehouse layout to reduce picking time by 15% and maintained inventory organisation across 300+ SKUs.",
                            Title = "Warehouse Assistant"
                        });
                });

            modelBuilder.Entity("PortfolioApi.Models.Interest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<string>("Subtitle")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Interests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Details = "Second Team Captain for Cardiff University, where I coach 25+ players and organize weekly training sessions. I also coach the Girls 15s team in East Wales for national competitions, training 16 athletes, and serve as a qualified International referee, officiating at the Touch Euros.",
                            Subtitle = "Cardiff Uni & Wales Touch Association",
                            Title = "Touch Rugby"
                        },
                        new
                        {
                            Id = 2,
                            Details = "Served for 5 years and was promoted to Cadet Flight Sergeant. During my service, I led training for 15+ junior cadets in the Part II syllabus and participated in 5+ flight and gliding field days.",
                            Subtitle = "KSW CCF",
                            Title = "Air Cadets"
                        },
                        new
                        {
                            Id = 3,
                            Details = "Started as a mentor for 8 first-year students, supporting their academic and social transition. Promoted to Senior Student Mentor, where I oversee 6 new mentors and coordinate structured development sessions.",
                            Subtitle = "Cardiff University",
                            Title = "Student Mentoring"
                        },
                        new
                        {
                            Id = 4,
                            Details = "Active player in the local Padel community. Enjoy the strategic, fast-paced nature of the game and regularly participate in matches to stay sharp and maintain fitness.",
                            Subtitle = "Recreational & Competitive",
                            Title = "Padel"
                        });
                });

            modelBuilder.Entity("PortfolioApi.Models.LearnMore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<string>("Subtitle")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LearnMores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Details = "I grew up playing the Xbox 360, and its 'Metro' UI remains one of the most iconic, snappy, and satisfying digital interfaces ever designed. I built this portfolio as a tribute to that era, proving that highly interactive, controller-style navigation can still feel incredible on the modern web.",
                            Subtitle = "The Inspiration",
                            Title = "Project Desire"
                        },
                        new
                        {
                            Id = 2,
                            Details = "This entire dashboard is built in React. The layout relies heavily on CSS Grid for the authentic, tightly-packed Metro tile system. I utilized React Portals to ensure the pop-up modals break out of their containment blocks and render perfectly centered over the sliding canvas.",
                            Subtitle = "React & CSS Grid",
                            Title = "Frontend Architecture"
                        },
                        new
                        {
                            Id = 3,
                            Details = "The architecture is powered by a custom .NET Minimal API backed by a PostgreSQL database, managed with Entity Framework Core. The frontend fetches data dynamically, allowing the portfolio to be updated via database entries rather than hardcoded React state.",
                            Subtitle = "C# .NET & PostgreSQL",
                            Title = "Backend Infrastructure"
                        },
                        new
                        {
                            Id = 4,
                            Details = "To make it feel like a real console, I implemented a custom spatial navigation system. The app calculates physical distances between DOM elements so you can use your D-Pad (Arrow Keys) to naturally glide between tiles, Q/E to change tabs, and Enter to select—just like having a controller in your hands.",
                            Subtitle = "Spatial Navigation",
                            Title = "Keyboard Controls"
                        },
                        new
                        {
                            Id = 5,
                            Details = "The Settings tab is currently a fun visual easter egg, but future updates will wire these tiles to global React Contexts. This will allow users to toggle dark modes, change accent colors, and manage the website's background audio just like a real Xbox system menu.",
                            Subtitle = "Future Features",
                            Title = "Settings Page"
                        });
                });

            modelBuilder.Entity("PortfolioApi.Models.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<string>("Gamerscore")
                        .HasColumnType("text");

                    b.Property<string>("JoinDate")
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Zone")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Profiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Hey, I'm a passionate Software Engineer who loves building clean, interactive user interfaces.<br/><br/>When I'm not writing React code or hunting down CSS bugs, you can usually find me exploring new tech stacks, designing game UI clones, or trying to beat my high scores.<br/><br/>My primary weapon of choice is JavaScript, but I'm always leveling up my skills in the backend and cloud infrastructure.",
                            Gamerscore = "15,420",
                            JoinDate = "2010",
                            Location = "UK",
                            Name = "William Hewston",
                            Zone = "Software Development"
                        });
                });

            modelBuilder.Entity("PortfolioApi.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<string>("Subtitle")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Details = "Experienced in building responsive and accessible user interfaces. Skilled in React, TailwindCSS, Bootstrap, and WordPress, with a focus on delivering high accessibility scores.",
                            Subtitle = "React, JavaScript, HTML/CSS",
                            Title = "Frontend Development"
                        },
                        new
                        {
                            Id = 2,
                            Details = "Proficient in server-side development using Java (Spring Boot), Python (Flask), and C# (.NET). Experienced in relational database management with PostgreSQL, MySQL, and MariaDB.",
                            Subtitle = "Java, Python, C#, SQL",
                            Title = "Backend & Databases"
                        },
                        new
                        {
                            Id = 3,
                            Details = "Strong understanding of DevOps practices including continuous integration and deployment using Jenkins. Familiar with containerisation (Docker), infrastructure as code (Terraform), Git source control, and Agile methodologies.",
                            Subtitle = "Git, Docker, CI/CD",
                            Title = "Tools & DevOps"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
